<?php

namespace OC\TicketsBundle\Repository;

/**
 * pricelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pricelistRepository extends \Doctrine\ORM\EntityRepository
{
}
