# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  oc.bookingbundle.opening:
    class: OC\BookingBundle\Service\Opening
    arguments: []

  oc.bookingbundle.utils:
    class: OC\BookingBundle\Service\Utils
    arguments: []

  oc.bookingbundle.booking:
    class: OC\BookingBundle\Service\Booking
    arguments: ["@doctrine.orm.entity_manager", '@service_container' ]

  oc.bookingbundle.price:
    class: OC\BookingBundle\Service\Price
    arguments: ["@doctrine.orm.entity_manager", '@service_container']
