# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    oc.ticketsbundle.opening:
        class: OC\TicketsBundle\Service\Opening
        arguments: []
