<?php

namespace OC\BookingBundle\Repository;

/**
 * visitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{

	public function getTotalAmount($ticket_id){

		$qb = $this->createQueryBuilder('v');

		$qb->andWhere('v.ticket = :ticket_id')
			->setParameter('ticket_id', $ticket_id)
			->select("SUM(v.amount) as total")
		;
		$result = $qb->getQuery()->getOneOrNullResult();
		return $result['total'];
	}
}
