oc_booking_select:
  path:     /
  defaults: { _controller: OCBookingBundle:Booking:select }
  methods: [get,post]

oc_booking_visitor:
  path:     /visitor
  defaults: { _controller: OCBookingBundle:Booking:visitor }
  methods: [get,post]

oc_booking_payment:
  path:     /payment
  defaults: { _controller: OCBookingBundle:Booking:payment }
  methods: [get,post]

oc_booking_checkout:
  path:     /checkout
  defaults: { _controller: OCBookingBundle:Booking:checkout }
  methods: [get,post]

oc_booking_ajax_opening:
  path:     /getOpening
  defaults: { _controller: OCBookingBundle:Ajax:getOpening }
  methods: [post]

oc_booking_ajax_listprice:
  path:     /getListprice
  defaults: { _controller: OCBookingBundle:Ajax:getListprice }
  methods: [post]
