services:
#    oc_tickets.example:
#        class: OC\TicketsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
oc.bookingbundle.listprice:
  class: OC\BookingBundle\Service\Listprice
  arguments: []